# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('willylistapp', '0005_auto_20170307_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
